// Generated from the SmartCare Assist project (healthcare-dss): frontend/i18n/{en,hi,mr}.json
// and the Clinical Guidance data in frontend/index.html. Do not edit by hand; see
// docs/SMARTCARE_WORKSPACE.md for how it was produced.

export const STRINGS = {
  "en": {
    "disclaimer_pcw": "Not a final diagnosis. AI suggestions are advisory only.",
    "disclaimer_label": "Clinical Disclaimer:",
    "lang_label": "🌐 Language:",
    "age_label": "Age (years):",
    "gender_label": "Gender:",
    "gender.male": "Male",
    "gender.female": "Female",
    "gender.other": "Other",
    "duration_label": "Duration (days):",
    "symptoms_legend": "Symptoms / Primary Complaints",
    "severity_label": "Intensity / Severity:",
    "submit_button": "Submit clinical assessment",
    "medical_history": "Relevant medical history:",
    "vitals_section": "Physical findings (Vitals):",
    "symptom.fever": "Fever",
    "symptom.cough": "Cough",
    "symptom.breathlessness": "Breathlessness",
    "symptom.chest_pain": "Chest pain",
    "symptom.rash": "Rash",
    "symptom.diarrhea": "Diarrhea",
    "symptom.vomiting": "Vomiting",
    "symptom.headache": "Headache",
    "symptom.abdominal_pain": "Abdominal pain",
    "symptom.fatigue": "Fatigue",
    "symptom.body_ache": "Body ache",
    "symptom.sore_throat": "Sore throat",
    "symptom.joint_pain": "Joint pain",
    "symptom.nausea": "Nausea",
    "symptom.dizziness": "Dizziness",
    "symptom.confusion": "Confusion",
    "symptom.swelling": "Swelling",
    "symptom.palpitations": "Palpitations",
    "severity.low": "Low",
    "severity.medium": "Moderate",
    "severity.high": "Severe",
    "reasoning_trail": "Clinical Reasoning Trail:",
    "summary_header": "AI Generation: Professional SOAP Summary",
    "heatmap_title": "Structured Risk Stratification Heatmap",
    "analyzing_case": "AI is analyzing clinical data...",
    "ai_suggestion": "Clinical Assessment Result",
    "voice_preview_placeholder": "Click Start and speak symptoms...",
    "chronic_conditions_label": "Chronic Conditions:",
    "history.diabetes": "Diabetes",
    "history.hypertension": "Hypertension",
    "history.heart_disease": "Heart Disease",
    "history.asthma": "Asthma/COPD",
    "history.kidney_disease": "Kidney Disease",
    "history.cancer": "Cancer",
    "soap.presentation": "PRESENTATION",
    "soap.findings": "PHYSICAL FINDINGS (VITALS)",
    "soap.assessment": "CLINICAL IMPRESSION",
    "soap.plan": "MANAGEMENT PLAN",
    "soap.age": "{{val}}-year-old",
    "soap.pregnant": "pregnant female",
    "soap.pregnant_weeks": "pregnant female at {{val}} weeks gestation",
    "soap.individual": "individual",
    "soap.complaints": "Primary complaints include: {{val}}.",
    "soap.history": "Significant medical history: {{val}}.",
    "soap.allergies": "Allergies: {{val}}.",
    "soap.meds": "Current medications: {{val}}.",
    "soap.vitals_abnormal": "Significant findings include: {{val}}.",
    "soap.vitals_normal": "Vital signs within expected parameters.",
    "soap.risk_profile": "Assessment indicates translatable profile (Score: {{score}}/100).",
    "soap.maternal_status": "Maternal status assessment: {{level}} (Score: {{score}}).",
    "soap.escalation_init": "Immediate escalation initiated (Level: {{level}}). Urgency: {{urgency}}.",
    "voice_assistant_title": "Voice Clinical Assistant",
    "voice_status_standby": "Standby",
    "voice_instructions": "Speak keywords like 'fever', 'cough' or durations like '3 days'",
    "voice_listening_placeholder": "Click 'Start Voice' to begin...",
    "final_transcript_label": "Final Transcript",
    "btn_reset": "RESET",
    "btn_start_recording": "🎤 Start Recording",
    "btn_stop_recording": "⏹️ Stop Recording",
    "voice_review_title": "Suggested Form Updates",
    "btn_apply_updates": "Apply Updates",
    "btn_discard": "Discard",
    "reftable.title": "Symptom → Condition Table",
    "reftable.col.symptom": "Symptom",
    "reftable.col.bodypart": "Body Part",
    "reftable.col.cancause": "Can Cause",
    "reftable.region.systemic": "General / Systemic",
    "reftable.region.chest": "Chest / Thoracic",
    "reftable.region.head": "Head / Cranial",
    "reftable.region.abdomen": "Abdomen",
    "reftable.region.neck": "Neck / Cervical",
    "reftable.region.limbs": "Limbs / Joints",
    "reftable.region.leg": "Leg / Lower Limb",
    "reftable.risk.fever": "Malaria, Typhoid, Dengue, Sepsis",
    "reftable.risk.cough": "Pneumonia, TB, Asthma, COVID-19",
    "reftable.risk.breathlessness": "COPD, Asthma, Heart Failure, PE",
    "reftable.risk.chest_pain": "⚡ Cardiac Arrest, Angina, Aortic Dissection",
    "reftable.risk.headache": "Hypertension, Meningitis, Migraine, Stroke",
    "reftable.risk.rash": "Dengue, Measles, Chickenpox, Allergy",
    "reftable.risk.diarrhea": "Cholera, Gastroenteritis, Food Poisoning",
    "reftable.risk.vomiting": "Gastritis, Appendicitis, Liver Issues",
    "reftable.risk.abdominal_pain": "Appendicitis, Ulcer, Ectopic Pregnancy, Kidney Stone",
    "reftable.risk.fatigue": "Anaemia, Thyroid Disorder, Diabetes, Infection",
    "reftable.risk.body_ache": "Dengue, Chikungunya, Influenza, Typhoid",
    "reftable.risk.sore_throat": "Strep Throat, Tonsillitis, Diphtheria",
    "reftable.risk.joint_pain": "Arthritis, Chikungunya, Lupus, Gout",
    "reftable.risk.nausea": "Gastroenteritis, Migraine, Pregnancy, Hepatitis",
    "reftable.risk.dizziness": "Vertigo, Hypoglycemia, BP Drop, Stroke TIA",
    "reftable.risk.confusion": "⚡ Encephalitis, Meningitis, Sepsis, Stroke",
    "reftable.risk.swelling": "DVT, Heart Failure, Kidney Disease, Lymphedema",
    "reftable.risk.palpitations": "Arrhythmia, Hyperthyroidism, Panic Attack, Anaemia",
    "reftable.risk.high_bp": "⚡ Hypertensive Crisis, Stroke, Renal Failure, HF",
    "symptom.high_bp": "High Blood Pressure"
  },
  "hi": {
    "disclaimer_pcw": "यह अंतिम निदान नहीं है। AI सुझाव केवल सलाहकार हैं।",
    "disclaimer_label": "नैदानिक अस्वीकरण:",
    "lang_label": "🌐 भाषा:",
    "age_label": "आयु (वर्ष):",
    "gender_label": "लिंग:",
    "gender.male": "पुरुष",
    "gender.female": "महिला",
    "gender.other": "अन्य",
    "duration_label": "अवधि (दिन):",
    "symptoms_legend": "लक्षण / प्राथमिक शिकायतें",
    "severity_label": "तीव्रता / गंभीरता:",
    "submit_button": "नैदानिक मूल्यांकन जमा करें",
    "medical_history": "प्रासंगिक चिकित्सा इतिहास:",
    "vitals_section": "शारीरिक निष्कर्ष (Vitals):",
    "symptom.fever": "बुखार",
    "symptom.cough": "खांसी",
    "symptom.breathlessness": "सांस फूलना",
    "symptom.chest_pain": "सीने में दर्द",
    "symptom.rash": "चकत्ते",
    "symptom.diarrhea": "दस्त",
    "symptom.vomiting": "उल्टी",
    "symptom.headache": "सिरदर्द",
    "symptom.abdominal_pain": "पेट दर्द",
    "symptom.fatigue": "थकान",
    "symptom.body_ache": "बदन दर्द",
    "symptom.sore_throat": "गला खराब",
    "symptom.joint_pain": "जोड़ों में दर्द",
    "symptom.nausea": "मिचली",
    "symptom.dizziness": "चक्कर आना",
    "symptom.confusion": "भ्रम",
    "symptom.swelling": "सूजन",
    "symptom.palpitations": "दिल की धड़कन बढ़ना",
    "severity.low": "कम",
    "severity.medium": "मध्यम",
    "severity.high": "गंभीर",
    "reasoning_trail": "नैदानिक विश्लेषण पथ:",
    "summary_header": "AI जनरेशन: पेशेवर SOAP सारांश",
    "heatmap_title": "संरचित जोखिम स्तरीकरण हीटमैप",
    "analyzing_case": "AI नैदानिक डेटा का विश्लेषण कर रहा है...",
    "ai_suggestion": "नैदानिक मूल्यांकन परिणाम",
    "voice_preview_placeholder": "प्रारंभ पर क्लिक करें और लक्षण बोलें...",
    "chronic_conditions_label": "पुरानी बीमारियाँ (Chronic Conditions):",
    "history.diabetes": "मधुमेह",
    "history.hypertension": "उच्च रक्तचाप",
    "history.heart_disease": "हृदय रोग",
    "history.asthma": "अस्थमा/COPD",
    "history.kidney_disease": "गुर्दे की बीमारी",
    "history.cancer": "कैंसर",
    "soap.presentation": "प्रस्तुति (PRESENTATION)",
    "soap.findings": "शारीरिक निष्कर्ष (Vitals)",
    "soap.assessment": "नैदानिक धारणा (Assessment)",
    "soap.plan": "प्रबंधन योजना (Plan)",
    "soap.age": "{{val}}-वर्षीय",
    "soap.pregnant": "गर्भवती महिला",
    "soap.pregnant_weeks": "{{val}} सप्ताह की गर्भवती महिला",
    "soap.individual": "व्यक्ति",
    "soap.complaints": "मुख्य शिकायतें शामिल हैं: {{val}}।",
    "soap.history": "महत्वपूर्ण चिकित्सा इतिहास: {{val}}।",
    "soap.allergies": "एलर्जी: {{val}}।",
    "soap.meds": "वर्तमान दवाएं: {{val}}।",
    "soap.vitals_abnormal": "महत्वपूर्ण निष्कर्षों में शामिल हैं: {{val}}।",
    "soap.vitals_normal": "रिकॉर्ड किए गए डेटा के आधार पर महत्वपूर्ण संकेत सामान्य हैं।",
    "soap.risk_profile": "मूल्यांकन {{level}} जोखिम प्रोफाइल (स्कोर: {{score}}/100) का संकेत देता है।",
    "soap.maternal_status": "मातृ स्थिति मूल्यांकन: {{level}} (स्कोर: {{score}})।",
    "soap.escalation_init": "तत्काल वृद्धि शुरू की गई (स्तर: {{level}})। तात्कालिकता: {{urgency}}।",
    "voice_assistant_title": "वॉयस क्लिनिकल असिस्टेंट",
    "voice_status_standby": "स्टैंडबाय",
    "voice_instructions": "कीवर्ड बोलें जैसे 'बुखार', 'खांसी' या अवधि जैसे '3 दिन'",
    "voice_listening_placeholder": "शुरू करने के लिए 'आवाज शुरू करें' पर क्लिक करें...",
    "final_transcript_label": "अंतिम प्रतिलेख",
    "btn_reset": "रीसेट करें",
    "btn_start_recording": "🎤 रिकॉर्डिंग शुरू करें",
    "btn_stop_recording": "⏹️ रिकॉर्डिंग बंद करें",
    "voice_review_title": "सुझाए गए फॉर्म अपडेट",
    "btn_apply_updates": "अपडेट लागू करें",
    "btn_discard": "खारिज करें",
    "reftable.title": "लक्षण → बीमारी तालिका",
    "reftable.col.symptom": "लक्षण",
    "reftable.col.bodypart": "शरीर का भाग",
    "reftable.col.cancause": "हो सकती है",
    "reftable.region.systemic": "सामान्य / दैहिक",
    "reftable.region.chest": "छाती / वक्ष",
    "reftable.region.head": "सिर / कपाल",
    "reftable.region.abdomen": "पेट / उदर",
    "reftable.region.neck": "गले / ग्रीवा",
    "reftable.region.limbs": "हाथ-पाँव / जोड़",
    "reftable.region.leg": "पैर / निचले अंग",
    "reftable.risk.fever": "मलेरिया, टाइफाइड, डेंगू, सेप्सिस",
    "reftable.risk.cough": "निमोनिया, TB, अस्थमा, COVID-19",
    "reftable.risk.breathlessness": "COPD, अस्थमा, हृदय विफलता, PE",
    "reftable.risk.chest_pain": "⚡ हृदय घात, एनजाइना, महाधमनी विच्छेदन",
    "reftable.risk.headache": "उच्च रक्तचाप, मेनिनजाइटिस, माइग्रेन, स्ट्रोक",
    "reftable.risk.rash": "डेंगू, खसरा, चेचक, एलर्जी",
    "reftable.risk.diarrhea": "हैजा, गैस्ट्रोएंटेराइटिस, फूड पॉइजनिंग",
    "reftable.risk.vomiting": "गैस्ट्राइटिस, अपेंडिसाइटिस, जिगर की समस्या",
    "reftable.risk.abdominal_pain": "अपेंडिसाइटिस, अल्सर, एक्टोपिक गर्भावस्था, गुर्दे की पथरी",
    "reftable.risk.fatigue": "एनीमिया, थायराइड विकार, मधुमेह, संक्रमण",
    "reftable.risk.body_ache": "डेंगू, चिकनगुनिया, इन्फ्लूएंजा, टाइफाइड",
    "reftable.risk.sore_throat": "स्ट्रेप गला, टॉन्सिलाइटिस, डिफ्थीरिया",
    "reftable.risk.joint_pain": "गठिया, चिकनगुनिया, ल्यूपस, गठिया रोग",
    "reftable.risk.nausea": "गैस्ट्रोएंटेराइटिस, माइग्रेन, गर्भावस्था, हेपेटाइटिस",
    "reftable.risk.dizziness": "वर्टिगो, हाइपोग्लाइसीमिया, BP गिरना, TIA स्ट्रोक",
    "reftable.risk.confusion": "⚡ एन्सेफलाइटिस, मेनिनजाइटिस, सेप्सिस, स्ट्रोक",
    "reftable.risk.swelling": "DVT, हृदय विफलता, गुर्दे की बीमारी, लिम्फेडेमा",
    "reftable.risk.palpitations": "अतालता, हाइपरथायरायडिज्म, पैनिक अटैक, एनीमिया",
    "reftable.risk.high_bp": "⚡ उच्च रक्तचाप संकट, स्ट्रोक, गुर्दे की विफलता",
    "symptom.high_bp": "उच्च रक्तचाप"
  },
  "mr": {
    "disclaimer_pcw": "हे अंतिम निदान नाही. AI सूचना केवळ सल्लागार आहेत.",
    "disclaimer_label": "वैद्यकीय अस्वीकरण:",
    "lang_label": "🌐 भाषा:",
    "age_label": "वय (वर्षे):",
    "gender_label": "लिंग:",
    "gender.male": "पुरुष",
    "gender.female": "स्त्री",
    "gender.other": "इतर",
    "duration_label": "कालावधी (दिवस):",
    "symptoms_legend": "लक्षणे / प्राथमिक तक्रारी",
    "severity_label": "तीव्रता / गांभीर्य:",
    "submit_button": "वैद्यकीय मूल्यांकन सादर करा",
    "medical_history": "संबंधित वैद्यकीय इतिहास:",
    "vitals_section": "शारीरिक निष्कर्ष (Vitals):",
    "symptom.fever": "ताप",
    "symptom.cough": "खोकला",
    "symptom.breathlessness": "दम लागणे",
    "symptom.chest_pain": "छातीत दुखणे",
    "symptom.rash": "पुरळ",
    "symptom.diarrhea": "जुलाब",
    "symptom.vomiting": "उलट्या",
    "symptom.headache": "डोकेदुखी",
    "symptom.abdominal_pain": "पोटदुखी",
    "symptom.fatigue": " थकवा",
    "symptom.body_ache": "अंगदुखी",
    "symptom.sore_throat": "घसा खवखवणे",
    "symptom.joint_pain": "सांधेदुखी",
    "symptom.nausea": "मळमळ",
    "symptom.dizziness": "चक्कर येणे",
    "symptom.confusion": "गोंधळ होणे",
    "symptom.swelling": "सूज",
    "symptom.palpitations": "धडधड होणे",
    "severity.low": "कमी",
    "severity.medium": "मध्यम",
    "severity.high": "गंभीर",
    "reasoning_trail": "वैद्यकीय विश्लेषण मार्ग:",
    "summary_header": "AI निर्मित: व्यावसायिक SOAP सारांश",
    "heatmap_title": "संरचित जोखीम स्तरीकरण हीटमैप",
    "analyzing_case": "AI वैद्यकीय माहितीचे विश्लेषण करत आहे...",
    "ai_suggestion": "नैदानिक मूल्यांकन निकाल",
    "voice_preview_placeholder": "प्रारंभ वर क्लिक करा आणि लक्षणे बोला...",
    "chronic_conditions_label": "दीर्घकालीन आजार (Chronic Conditions):",
    "history.diabetes": "मधुमेह",
    "history.hypertension": "उच्च रक्तदाब",
    "history.heart_disease": "हदयविकार",
    "history.asthma": "अस्थमा/COPD",
    "history.kidney_disease": "मूत्रपिंडाचा आजार",
    "history.cancer": "कर्करोग",
    "soap.presentation": "रुग्णाची परिस्थिती (PRESENTATION)",
    "soap.findings": "शारीरिक निष्कर्ष (Vitals)",
    "soap.assessment": "वैद्यकीय मत (Assessment)",
    "soap.plan": "व्यवस्थापन योजना (Plan)",
    "soap.age": "{{val}}-वर्षीय",
    "soap.pregnant": "गर्भवती महिला",
    "soap.pregnant_weeks": "{{val}} आठवड्यांची गर्भवती महिला",
    "soap.individual": "व्यक्ती",
    "soap.complaints": "मुख्य तक्रारींमध्ये समाविष्ट आहे: {{val}}.",
    "soap.history": "महत्त्वाचा वैद्यकीय इतिहास: {{val}}.",
    "soap.allergies": "ॲलर्जी: {{val}}.",
    "soap.meds": "सध्याची औषधे: {{val}}.",
    "soap.vitals_abnormal": "महत्त्वाच्या निष्कर्षांमध्ये समाविष्ट आहे: {{val}}.",
    "soap.vitals_normal": "नोंदवलेल्या माहितीनुसार शारीरिक निष्कर्ष सामान्य आहेत.",
    "soap.risk_profile": "मूल्यांकन {{level}} जोखीम प्रोफाइल (स्कोअर: {{score}}/१००) सूचित करते.",
    "soap.maternal_status": "मातृ स्थिती मूल्यांकन: {{level}} (स्कोअर: {{score}}).",
    "soap.escalation_init": "तात्काळ वाढ सुरू केली आहे (स्तर: {{level}}). तात्कालिकता: {{urgency}}.",
    "voice_assistant_title": "व्हॉइस क्लिनिकल असिस्टंट",
    "voice_status_standby": "स्टँडबाय",
    "voice_instructions": "कीवर्ड बोला जसे 'ताप', 'खोकला' किंवा कालावधी जसे '३ दिवस'",
    "voice_listening_placeholder": "सुरू करण्यासाठी 'आवाज सुरू करा' वर क्लिक करा...",
    "final_transcript_label": "अंतिम प्रतिलेख",
    "btn_reset": "रीसेट करा",
    "btn_start_recording": "🎤 रेकॉर्डिंग सुरू करा",
    "btn_stop_recording": "⏹️ रेकॉर्डिंग थांबवा",
    "voice_review_title": "सुचवलेले फॉर्म अपडेट्स",
    "btn_apply_updates": "अपडेट लागू करा",
    "btn_discard": "काढून टाका",
    "reftable.title": "लक्षण → आजार सारणी",
    "reftable.col.symptom": "लक्षण",
    "reftable.col.bodypart": "शरीराचा भाग",
    "reftable.col.cancause": "होऊ शकते",
    "reftable.region.systemic": "सामान्य / शरीरव्यापी",
    "reftable.region.chest": "छाती / वक्ष",
    "reftable.region.head": "डोके / कपाल",
    "reftable.region.abdomen": "पोट / उदर",
    "reftable.region.neck": "घसा / ग्रीवा",
    "reftable.region.limbs": "हात-पाय / सांधे",
    "reftable.region.leg": "पाय / खालचे अंग",
    "reftable.risk.fever": "मलेरिया, विषमज्वर, डेंग्यू, सेप्सिस",
    "reftable.risk.cough": "न्यूमोनिया, क्षयरोग, दमा, COVID-19",
    "reftable.risk.breathlessness": "COPD, दमा, हृदय निकामी, PE",
    "reftable.risk.chest_pain": "⚡ हृदयविकाराचा झटका, एनजाइना, महाधमनी विच्छेदन",
    "reftable.risk.headache": "उच्च रक्तदाब, मेंदूज्वर, मायग्रेन, स्ट्रोक",
    "reftable.risk.rash": "डेंग्यू, गोवर, कांजिण्या, ऍलर्जी",
    "reftable.risk.diarrhea": "कॉलरा, आतड्यांचा दाह, अन्नबाधा",
    "reftable.risk.vomiting": "जठराचा दाह, आंत्रपुच्छाचा दाह, यकृताचे विकार",
    "reftable.risk.abdominal_pain": "आंत्रपुच्छाचा दाह, व्रण, एक्टोपिक गर्भधारणा, मूत्रपिंड दगड",
    "reftable.risk.fatigue": "अशक्तपणा, थायरॉईड विकार, मधुमेह, संसर्ग",
    "reftable.risk.body_ache": "डेंग्यू, चिकनगुन्या, इन्फ्लूएंझा, विषमज्वर",
    "reftable.risk.sore_throat": "स्ट्रेप घसा, टॉन्सिलायटिस, घटसर्प",
    "reftable.risk.joint_pain": "संधिवात, चिकनगुन्या, ल्युपस, गाउट",
    "reftable.risk.nausea": "आतड्यांचा दाह, मायग्रेन, गर्भधारणा, हिपॅटायटीस",
    "reftable.risk.dizziness": "वर्टिगो, रक्तशर्करा कमी, BP घट, TIA स्ट्रोक",
    "reftable.risk.confusion": "⚡ एन्सेफलायटीस, मेंदूज्वर, सेप्सिस, स्ट्रोक",
    "reftable.risk.swelling": "DVT, हृदय निकामी, मूत्रपिंड विकार, लिम्फेडेमा",
    "reftable.risk.palpitations": "अनियमित हृदयगती, हायपरथायरॉईडिझम, पॅनिक अटॅक, अशक्तपणा",
    "reftable.risk.high_bp": "⚡ उच्च रक्तदाब संकट, स्ट्रोक, मूत्रपिंड निकामी",
    "symptom.high_bp": "उच्च रक्तदाब"
  }
}

export const GUIDANCE = {
  "en": {
    "idle": {
      "region": "No region selected",
      "text": "Touch a body region on the map above to get real-time clinical guidance.",
      "tip": null,
      "icon": "🩺"
    },
    "head": {
      "region": "🧠 Cranial / Head Region",
      "text": "Check for: Headache, dizziness, blurred vision, confusion, or neck stiffness. Ask the patient if pain is sudden-onset or worsening.",
      "tip": "🚨 Red Flag: Sudden severe headache + neck stiffness may indicate Meningitis. Escalate immediately.",
      "icon": "🧠"
    },
    "neck": {
      "region": "🔗 Cervical / Neck Region",
      "text": "Check for: Swollen lymph nodes, sore throat, stiffness, or difficulty swallowing. Assess if pain radiates to the jaw or shoulder.",
      "tip": "⚠️ Alert: Neck stiffness with fever and headache is the Meningitic Triad — critical sign.",
      "icon": "🔗"
    },
    "chest": {
      "region": "❤️ Thoracic / Chest Region",
      "text": "Check for: Chest pain, palpitations, breathlessness, or cough. Note: Is pain crushing/squeezing? Does it radiate to the left arm?",
      "tip": "🚨 Red Flag: Crushing chest pain + breathlessness = possible cardiac event. Call emergency now.",
      "icon": "❤️"
    },
    "abdomen": {
      "region": "🫃 Abdominal Region",
      "text": "Check for: Abdominal pain, nausea, vomiting, diarrhea, or bloating. Ask about pain location — upper right may indicate liver/gallbladder.",
      "tip": "⚠️ Alert: Severe right-lower pain in a young woman may indicate appendicitis or ectopic pregnancy.",
      "icon": "🫃"
    },
    "rightArm": {
      "region": "💪 Right Upper Limb",
      "text": "Check for: Joint pain, swelling, weakness, or numbness. Assess grip strength and range of motion. Check for IV site complications.",
      "tip": null,
      "icon": "💪"
    },
    "leftArm": {
      "region": "💪 Left Upper Limb",
      "text": "Check for: Joint pain, swelling, or numbness. Pain radiating from chest to left arm is a cardiac red flag — verify immediately.",
      "tip": "🚨 Red Flag: Left arm pain with chest tightness = possible Acute Coronary Syndrome.",
      "icon": "🫀"
    },
    "rightLeg": {
      "region": "🦵 Right Lower Limb",
      "text": "Check for: Swelling, redness, warmth, or pain in the calf. Unilateral calf swelling is a classic DVT sign.",
      "tip": "⚠️ Alert: Unilateral calf swelling + redness = possible Deep Vein Thrombosis. Refer urgently.",
      "icon": "🦵"
    },
    "leftLeg": {
      "region": "🦵 Left Lower Limb",
      "text": "Check for: Swelling, redness, warmth, or pain in the calf or thigh. Check for ulcers in diabetic patients.",
      "tip": "⚠️ Alert: In diabetic patients, leg ulcers or numbness need urgent wound assessment.",
      "icon": "🦵"
    },
    "systemic": {
      "region": "🌐 Systemic / General Symptoms",
      "text": "Check for: Generalized fatigue, fever, body ache, weight loss, or rash. Consider systemic infection, autoimmune, or metabolic cause.",
      "tip": "⚠️ Alert: Fever + rash + joint pain may indicate Dengue, Chikungunya, or Measles.",
      "icon": "🌐"
    }
  },
  "hi": {
    "idle": {
      "region": "कोई अंग नहीं चुना",
      "text": "रीयल-टाइम क्लिनिकल मार्गदर्शन के लिए ऊपर दिए शरीर के नक्शे पर कोई अंग छुएं।",
      "tip": null,
      "icon": "🩺"
    },
    "head": {
      "region": "🧠 मस्तिष्क / सिर क्षेत्र",
      "text": "जांचें: सिरदर्द, चक्कर, धुंधली दृष्टि, भ्रम या गर्दन में अकड़न। पूछें कि दर्द अचानक शुरू हुआ या धीरे-धीरे बढ़ा।",
      "tip": "🚨 चेतावनी: अचानक तेज सिरदर्द + गर्दन की अकड़न = मेनिनजाइटिस का संकेत। तुरंत आगे भेजें।",
      "icon": "🧠"
    },
    "neck": {
      "region": "🔗 ग्रीवा / गर्दन क्षेत्र",
      "text": "जांचें: सूजी हुई ग्रंथियां, गले में खराश, या जबड़े/कंधे तक दर्द का फैलाव।",
      "tip": "⚠️ चेतावनी: बुखार के साथ गर्दन की अकड़न = मेनिनजाइटिस ट्रायड — अत्यंत गंभीर संकेत।",
      "icon": "🔗"
    },
    "chest": {
      "region": "❤️ वक्ष / छाती क्षेत्र",
      "text": "जांचें: सीने में दर्द, धड़कन, सांस लेने में कठिनाई या खांसी। क्या दर्द बाएं हाथ तक फैल रहा है?",
      "tip": "🚨 चेतावनी: भारी सीने का दर्द + सांस की तकलीफ = हृदय आपातकाल हो सकता है।",
      "icon": "❤️"
    },
    "abdomen": {
      "region": "🫃 पेट क्षेत्र",
      "text": "जांचें: पेट दर्द, मतली, उल्टी, दस्त। ऊपरी दाएं हिस्से का दर्द — लिवर/पित्ताशय की समस्या हो सकती है।",
      "tip": "⚠️ चेतावनी: युवा महिला में निचले दाएं दर्द — एपेंडिसाइटिस या एक्टोपिक प्रेग्नेंसी की जांच करें।",
      "icon": "🫃"
    },
    "rightArm": {
      "region": "💪 दाहिना ऊपरी अंग",
      "text": "जांचें: जोड़ों का दर्द, सूजन, कमजोरी, या सुन्नपन। पकड़ने की ताकत और गति की जांच करें।",
      "tip": null,
      "icon": "💪"
    },
    "leftArm": {
      "region": "💪 बायां ऊपरी अंग",
      "text": "जांचें: दर्द, सूजन, या सुन्नपन। सीने से बाएं हाथ तक दर्द = हृदय का लाल संकेत।",
      "tip": "🚨 चेतावनी: बाएं हाथ में दर्द + सीने में जकड़न = एक्यूट कोरोनरी सिंड्रोम।",
      "icon": "🫀"
    },
    "rightLeg": {
      "region": "🦵 दाहिना निचला अंग",
      "text": "जांचें: पिंडली में सूजन, लालिमा, गर्माहट। एक तरफ की पिंडली की सूजन = DVT का संकेत।",
      "tip": "⚠️ चेतावनी: एकतरफा सूजन + लालिमा = डीप वेन थ्रोम्बोसिस — तत्काल रेफर करें।",
      "icon": "🦵"
    },
    "leftLeg": {
      "region": "🦵 बायां निचला अंग",
      "text": "जांचें: सूजन, दर्द या घाव। मधुमेह रोगियों में पैर के घाव की तुरंत जांच करें।",
      "tip": "⚠️ चेतावनी: मधुमेह + पैर में घाव या सुन्नपन = तत्काल आकलन जरूरी।",
      "icon": "🦵"
    },
    "systemic": {
      "region": "🌐 सामान्य / पूरे शरीर के लक्षण",
      "text": "जांचें: थकान, बुखार, अंगदुखी, वजन घटना या रैश। प्रणालीगत संक्रमण या मेटाबोलिक कारण पर विचार करें।",
      "tip": "⚠️ चेतावनी: बुखार + रैश + जोड़ों का दर्द = डेंगू, चिकनगुनिया या खसरे की जांच करें।",
      "icon": "🌐"
    }
  },
  "mr": {
    "idle": {
      "region": "कोणताही भाग निवडलेला नाही",
      "text": "वरील शरीराच्या नकाशावर कोणताही भाग स्पर्श करा आणि त्वरित क्लिनिकल मार्गदर्शन मिळवा.",
      "tip": null,
      "icon": "🩺"
    },
    "head": {
      "region": "🧠 मस्तिष्क / डोके क्षेत्र",
      "text": "तपासा: डोकेदुखी, चक्कर, अंधुक दृष्टी, गोंधळ किंवा मानेत ताठरपणा। वेदना अचानक सुरू झाली का?",
      "tip": "🚨 धोकादायक: अचानक तीव्र डोकेदुखी + मानेत ताठरपणा = मेनिंजायटिसचा संकेत. तातडीने पाठवा.",
      "icon": "🧠"
    },
    "neck": {
      "region": "🔗 मान / ग्रीवा क्षेत्र",
      "text": "तपासा: सुजलेल्या ग्रंथी, घसा दुखणे, ताठरपणा किंवा जबडा/खांद्यापर्यंत वेदना।",
      "tip": "⚠️ सूचना: ताप + मानेत ताठरपणा = मेनिंजायटिस ट्रायड — अत्यंत गंभीर.",
      "icon": "🔗"
    },
    "chest": {
      "region": "❤️ छाती / वक्ष क्षेत्र",
      "text": "तपासा: छातीत दुखणे, धडधड, श्वास लेण्यात अडचण किंवा खोकला. वेदना डाव्या हाताकडे पसरत आहे का?",
      "tip": "🚨 धोकादायक: जड छातीत दुखणे + श्वास कमी होणे = हृदयाची आपत्कालीन स्थिती.",
      "icon": "❤️"
    },
    "abdomen": {
      "region": "🫃 पोट क्षेत्र",
      "text": "तपासा: पोटदुखी, मळमळ, उलटी, जुलाब. वरच्या उजव्या भागात दुखणे = यकृत/पित्ताशयाची समस्या असू शकते.",
      "tip": "⚠️ सूचना: तरुण स्त्रीमध्ये खालच्या उजव्या भागात वेदना — अपेंडिसायटिस किंवा एक्टोपिक गर्भधारणेची तपासणी करा.",
      "icon": "🫃"
    },
    "rightArm": {
      "region": "💪 उजवा वरचा अवयव",
      "text": "तपासा: सांधेदुखी, सूज, अशक्तपणा किंवा बधिरता. पकडण्याची शक्ती आणि हालचालींची तपासणी करा.",
      "tip": null,
      "icon": "💪"
    },
    "leftArm": {
      "region": "💪 डावा वरचा अवयव",
      "text": "तपासा: दुखणे, सूज किंवा बधिरता. छातीतून डाव्या हातापर्यंत वेदना = हृदयाचा लाल संकेत.",
      "tip": "🚨 धोकादायक: डाव्या हातात दुखणे + छातीत जडपणा = एक्यूट कोरोनरी सिंड्रोम.",
      "icon": "🫀"
    },
    "rightLeg": {
      "region": "🦵 उजवा खालचा अवयव",
      "text": "तपासा: वासरूमध्ये सूज, लालसरपणा, उबदारपणा. एकतर्फी वासरूची सूज = DVT चा संकेत.",
      "tip": "⚠️ सूचना: एकतर्फी सूज + लालसरपणा = डीप वेन थ्रोम्बोसिस — तातडीने संदर्भ द्या.",
      "icon": "🦵"
    },
    "leftLeg": {
      "region": "🦵 डावा खालचा अवयव",
      "text": "तपासा: सूज, वेदना किंवा जखम. मधुमेही रुग्णांमध्ये पायाच्या जखमांची त्वरित तपासणी करा.",
      "tip": "⚠️ सूचना: मधुमेह + पायात जखम = तातडीने मूल्यांकन आवश्यक.",
      "icon": "🦵"
    },
    "systemic": {
      "region": "🌐 सामान्य / संपूर्ण शरीराची लक्षणे",
      "text": "तपासा: थकवा, ताप, अंगदुखी, वजन कमी होणे किंवा पुरळ. पद्धतशीर संसर्ग किंवा चयापचय कारण विचारात घ्या.",
      "tip": "⚠️ सूचना: ताप + पुरळ + सांधेदुखी = डेंग्यू, चिकुनगुनिया किंवा गोवर तपासा.",
      "icon": "🌐"
    }
  }
}
